version: '2'
networks:
  swf:
services:
  jenkins2:
    # Docker image built from github.com/mgreau/dockerfiles/jenkins2
    image: mgreau/jenkins2:2.46.2
    container_name: exo-jenkins2
    environment: 
      - JENKINS_OPTS="-Dmail.smtp.starttls.enable='true'"
    ports:
      - "8888:8080"
      - "50001:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/jenkins_home
      - ~/.ssh/id_rsa.pub:/usr/share/jenkins/ref/.ssh/authorized_keys:rw
    networks:
      - swf
    privileged: true
    #restart: always  
  git:
    image: gogs/gogs
    container_name: gogs
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /Users/mgreau/SWF/gogs:/data
    networks:
      - swf
  mail:
    image: mailhog/mailhog
    container_name: smtp
    environment:
      MH_HOSTNAME: localhost
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_API_BIND_ADDR: 0.0.0.0:8025
      MH_UI_BIND_ADDR: 0.0.0.0:8025
      #MH_UI_WEB_PATH: mail
    ports: 
      - "8025:8025"
    networks:
      - swf
