version: "2"
services:
  slides:
    # Docker image built from github.com/mgreau/dockerfiles/asciidoctor-bespoke/exo-ioslides
    image: mgreau/asciidoctor-bespoke:exo-ioslides
    ports:
      - "8000:8000"
      - "35729"
    volumes:
      - ./slides:/documents/slides
    container_name: 'dday'
